### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by bnookala** [felixrieseberg/windows-build-tools#3]
```
C:\Users\bhargav\code\windows-build-tools [master ↑]> npm install

> windows-build-tools@0.1.5 postinstall C:\Users\bhargav\code\windows-build-tools
> node ./lib/index.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\Users\bhargav\code\windows-build-tools\lib\index.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Windows_NT 10.0.14352
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! windows-build-tools@0.1.5 postinstall: `node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@0.1.5 postinstall script 'node ./lib/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the windows-build-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs windows-build-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bhargav\code\windows-build-tools\npm-debug.log
```

Oddly enough, I *also* can't get babel to build the index itself, even though it's installed into node_modules:

```
C:\Users\bhargav\code\windows-build-tools [master ↑]> npm run build

> windows-build-tools@0.1.5 build C:\Users\bhargav\code\windows-build-tools
> babel src --preset es2015 -d lib

'babel' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14352
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! windows-build-tools@0.1.5 build: `babel src --preset es2015 -d lib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@0.1.5 build script 'babel src --preset es2015 -d lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the windows-build-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src --preset es2015 -d lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs windows-build-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bhargav\code\windows-build-tools\npm-debug.log
```

**Comment by felixrieseberg** [comment]
Fixed!

**Comment by bnookala** [comment]
@felixrieseberg Still getting this error, even after pulling your latest changes :(

**Comment by pmcbiker** [comment]
I get error installing windows-build-tools

C:\node_modules>npm install --global --production windows-build-tools
npm http GET https://registry.npmjs.org/windows-build-tools
npm http 304 https://registry.npmjs.org/windows-build-tools
npm WARN engine windows-build-tools@0.6.0: wanted: {"node":">=4.0.0"} (current:
{"node":"v0.10.26","npm":"1.4.3"})
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/cli-spinner
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/nugget
npm http 304 https://registry.npmjs.org/cli-spinner
npm http 304 https://registry.npmjs.org/fs-extra
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/nugget
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/pretty-bytes
npm http GET https://registry.npmjs.org/single-line-log
npm http GET https://registry.npmjs.org/throttleit/0.0.2
npm http GET https://registry.npmjs.org/progress-stream
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/klaw
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/path-is-absolute
npm http GET https://registry.npmjs.org/jsonfile
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/single-line-log
npm http 304 https://registry.npmjs.org/throttleit/0.0.2
npm http 304 https://registry.npmjs.org/pretty-bytes
npm http 304 https://registry.npmjs.org/jsonfile
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/progress-stream
npm http 304 https://registry.npmjs.org/klaw
npm http GET https://registry.npmjs.org/meow
npm http GET https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/speedometer
npm http GET https://registry.npmjs.org/through2
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/aws4
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/bl
npm http GET https://registry.npmjs.org/har-validator
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/is-typedarray
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/isstream
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/meow
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/get-stdin
npm http 304 https://registry.npmjs.org/speedometer
npm http 304 https://registry.npmjs.org/through2
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/decamelize
npm http GET https://registry.npmjs.org/normalize-package-data
npm http GET https://registry.npmjs.org/object-assign
npm http GET https://registry.npmjs.org/map-obj
npm http GET https://registry.npmjs.org/read-pkg-up
npm http GET https://registry.npmjs.org/redent
npm http GET https://registry.npmjs.org/trim-newlines
npm http GET https://registry.npmjs.org/loud-rejection
npm http GET https://registry.npmjs.org/camelcase-keys
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/aws4
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/is-typedarray
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/caseless
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/har-validator
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/fs.realpath
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/decamelize
npm http 304 https://registry.npmjs.org/object-assign
npm http 304 https://registry.npmjs.org/trim-newlines
npm http 304 https://registry.npmjs.org/map-obj
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/redent
npm http 304 https://registry.npmjs.org/camelcase-keys
npm http 304 https://registry.npmjs.org/normalize-package-data
npm http 304 https://registry.npmjs.org/read-pkg-up
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"v0.1
0.26","npm":"1.4.3"})
npm http 304 https://registry.npmjs.org/loud-rejection
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/fs.realpath
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/delayed-stream
npm http GET https://registry.npmjs.org/camelcase
npm http GET https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/indent-string
npm http GET https://registry.npmjs.org/strip-indent
npm http GET https://registry.npmjs.org/find-up
npm http GET https://registry.npmjs.org/read-pkg
npm http GET https://registry.npmjs.org/signal-exit
npm http GET https://registry.npmjs.org/currently-unhandled
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/object-keys
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/find-up
npm http 304 https://registry.npmjs.org/strip-indent
npm http 304 https://registry.npmjs.org/read-pkg
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/indent-string
npm http 304 https://registry.npmjs.org/delayed-stream
npm http GET https://registry.npmjs.org/sshpk
npm http GET https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/jsprim
npm http 304 https://registry.npmjs.org/currently-unhandled
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/signal-exit
npm http GET https://registry.npmjs.org/is-my-json-valid
npm http GET https://registry.npmjs.org/pinkie-promise
npm http GET https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/object-keys
npm http 304 https://registry.npmjs.org/sshpk
npm http 304 https://registry.npmjs.org/jsprim
npm http 304 https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/path-exists
npm http GET https://registry.npmjs.org/load-json-file
npm http GET https://registry.npmjs.org/repeating
npm http GET https://registry.npmjs.org/path-type
npm http 304 https://registry.npmjs.org/pinkie-promise
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/is-my-json-valid
npm http GET https://registry.npmjs.org/array-find-index
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/load-json-file
npm http 304 https://registry.npmjs.org/path-type
npm http 304 https://registry.npmjs.org/path-exists
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/repeating
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/array-find-index
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/pinkie
npm http GET https://registry.npmjs.org/extsprintf/1.0.2
npm http GET https://registry.npmjs.org/verror/1.3.6
npm http GET https://registry.npmjs.org/json-schema/0.2.2
npm http GET https://registry.npmjs.org/pify
npm http GET https://registry.npmjs.org/hosted-git-info
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/is-builtin-module
npm http GET https://registry.npmjs.org/validate-npm-package-license
npm http GET https://registry.npmjs.org/parse-json
npm http 304 https://registry.npmjs.org/pinkie
npm http GET https://registry.npmjs.org/strip-bom
npm http 304 https://registry.npmjs.org/extsprintf/1.0.2
npm http 304 https://registry.npmjs.org/json-schema/0.2.2
npm http 304 https://registry.npmjs.org/verror/1.3.6
npm http 304 https://registry.npmjs.org/pify
npm http GET https://registry.npmjs.org/is-finite
npm http GET https://registry.npmjs.org/graceful-readlink
npm http 304 https://registry.npmjs.org/hosted-git-info
npm http 304 https://registry.npmjs.org/parse-json
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/is-builtin-module
npm http 304 https://registry.npmjs.org/validate-npm-package-license
npm http 304 https://registry.npmjs.org/strip-bom
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http 304 https://registry.npmjs.org/is-finite
npm http GET https://registry.npmjs.org/isarray
npm http GET https://registry.npmjs.org/process-nextick-args
npm http GET https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/isarray
npm http GET https://registry.npmjs.org/is-utf8
npm http GET https://registry.npmjs.org/builtin-modules
npm http 304 https://registry.npmjs.org/process-nextick-args
npm http 304 https://registry.npmjs.org/util-deprecate
npm http GET https://registry.npmjs.org/number-is-nan
npm http GET https://registry.npmjs.org/spdx-correct
npm http GET https://registry.npmjs.org/spdx-expression-parse
npm http 304 https://registry.npmjs.org/builtin-modules
npm http 304 https://registry.npmjs.org/is-utf8
npm http GET https://registry.npmjs.org/error-ex
npm http 304 https://registry.npmjs.org/number-is-nan
npm http 304 https://registry.npmjs.org/spdx-correct
npm http 304 https://registry.npmjs.org/spdx-expression-parse
npm http 304 https://registry.npmjs.org/error-ex
npm http GET https://registry.npmjs.org/is-arrayish
npm http GET https://registry.npmjs.org/spdx-license-ids
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/asn1
npm http GET https://registry.npmjs.org/jsbn
npm http GET https://registry.npmjs.org/dashdash
npm http GET https://registry.npmjs.org/tweetnacl
npm http GET https://registry.npmjs.org/ecc-jsbn
npm http GET https://registry.npmjs.org/jodid25519
npm http GET https://registry.npmjs.org/getpass
npm http 304 https://registry.npmjs.org/is-arrayish
npm http 304 https://registry.npmjs.org/spdx-license-ids
npm http GET https://registry.npmjs.org/generate-function
npm http GET https://registry.npmjs.org/jsonpointer/2.0.0
npm http GET https://registry.npmjs.org/generate-object-property
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/asn1
npm http 304 https://registry.npmjs.org/tweetnacl
npm http 304 https://registry.npmjs.org/getpass
npm http 304 https://registry.npmjs.org/jodid25519
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"v0.
10.26","npm":"1.4.3"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":
"v0.10.26","npm":"1.4.3"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"v0.
10.26","npm":"1.4.3"})
npm http 304 https://registry.npmjs.org/ecc-jsbn
npm http 304 https://registry.npmjs.org/jsbn
npm http 304 https://registry.npmjs.org/dashdash
npm http 304 https://registry.npmjs.org/generate-function
npm http 304 https://registry.npmjs.org/generate-object-property
npm http 304 https://registry.npmjs.org/jsonpointer/2.0.0
npm http GET https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/is-property
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/lodash

> windows-build-tools@0.6.0 postinstall C:\Users\zitellir\AppData\Roaming\npm\no
de_modules\windows-build-tools
> node ./lib/index.js


C:\Users\zitellir\AppData\Roaming\npm\node_modules\windows-build-tools\lib\insta
ll\tailer.js:9
f (typeof superClass !== "function" && superClass !== null) { throw new TypeEr
                                                                    ^
TypeError: Super expression must either be null or a function, not object
    at _inherits (C:\Users\zitellir\AppData\Roaming\npm\node_modules\windows-bui
ld-tools\lib\install\tailer.js:9:113)
    at C:\Users\zitellir\AppData\Roaming\npm\node_modules\windows-build-tools\li
b\install\tailer.js:19:3
    at Object.<anonymous> (C:\Users\zitellir\AppData\Roaming\npm\node_modules\wi
ndows-build-tools\lib\install\tailer.js:140:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\zitellir\AppData\Roaming\npm\node_modules\wi
ndows-build-tools\lib\install\index.js:11:14)
npm ERR! windows-build-tools@0.6.0 postinstall: `node ./lib/index.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the windows-build-tools@0.6.0 postinstall script.
npm ERR! This is most likely a problem with the windows-build-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--production" "wi
ndows-build-tools"
npm ERR! cwd C:\node_modules
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\node_modules\npm-debug.log
npm ERR! not ok code 0

**Comment by bchr02** [comment]
@pmcbiker I believe the below snippet from you log explains why it's not workin for you:

npm WARN engine windows-build-tools@0.6.0: wanted: {"node":">=4.0.0"} (current:
{"node":"v0.10.26","npm":"1.4.3"})

**Comment by ecuriotto** [comment]
so how to install windows-build tools if for any reasons we are forced to use an older version of node?
